basePath: /api/v1
definitions:
  entity.Bottle:
    properties:
      description:
        type: string
      maturityDate:
        type: string
      title:
        type: string
      userId:
        type: string
    type: object
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /bottle:
    get:
      consumes:
      - application/json
      description: get string by ID
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Bottle'
      summary: Show an account
      tags:
      - bottles
    post:
      consumes:
      - application/json
      description: 새로운 유리병을 생성합니다.\n 유리병의 이름을 입력할 수 있습니다. 아무값 없이 요청하면 "default" 이름을
        갖게 됩니다.
      parameters:
      - description: Bottle name
        in: body
        name: name
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Bottle'
      summary: Create BOTTLE by userID
      tags:
      - bottles
  /bottles:
    get:
      consumes:
      - application/json
      description: GET bottle list
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Bottle'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: 유리병 목록 조회
      tags:
      - bottles
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
